# Generated by Django 5.2.7 on 2025-10-21 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_no', models.CharField(max_length=120)),
                ('license_file_ref', models.CharField(blank=True, max_length=120)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('license_stage_or_worktype', models.CharField(blank=True, max_length=120)),
                ('license_status', models.CharField(blank=True, max_length=60)),
                ('project_description', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('plot_no', models.CharField(blank=True, max_length=120)),
                ('plot_address', models.CharField(blank=True, max_length=120)),
                ('plot_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('consultant_name', models.CharField(blank=True, max_length=200)),
                ('consultant_license_no', models.CharField(blank=True, max_length=120)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('contractor_license_no', models.CharField(blank=True, max_length=120)),
                ('technical_decision_ref', models.CharField(blank=True, max_length=120)),
                ('technical_decision_date', models.DateField(blank=True, null=True)),
                ('license_notes', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('road_name', models.CharField(blank=True, max_length=120)),
                ('plot_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plot_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_no', models.CharField(blank=True, max_length=120)),
                ('plot_address', models.CharField(blank=True, max_length=120)),
                ('construction_status', models.CharField(blank=True, max_length=120)),
                ('allocation_type', models.CharField(blank=True, max_length=120)),
                ('land_use', models.CharField(blank=True, max_length=200)),
                ('base_district', models.CharField(blank=True, max_length=200)),
                ('overlay_district', models.CharField(blank=True, max_length=200)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('project_no', models.CharField(blank=True, max_length=120)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('developer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('application_number', models.CharField(blank=True, max_length=120)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siteplan', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitePlanOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('right_hold_type', models.CharField(blank=True, max_length=120)),
                ('share_and_acquisition', models.CharField(blank=True, max_length=120)),
                ('siteplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='projects.siteplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
