# Generated by Django 5.1.3 on 2025-11-03 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildinglicense',
            old_name='license_file_ref',
            new_name='land_plan_no',
        ),
        migrations.RenameField(
            model_name='buildinglicense',
            old_name='license_stage_or_worktype',
            new_name='land_use',
        ),
        migrations.RenameField(
            model_name='siteplanowner',
            old_name='share_and_acquisition',
            new_name='share_possession',
        ),
        migrations.RemoveField(
            model_name='buildinglicense',
            name='license_status',
        ),
        migrations.RemoveField(
            model_name='buildinglicense',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='buildinglicense',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.RemoveField(
            model_name='siteplanowner',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='building_license_file',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='land_use_sub',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='last_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='license_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='project_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='siteplan_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('new', 'New Contract'), ('continue', 'Continuation Contract')], max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('villa', 'Villa'), ('commercial', 'Commercial'), ('maintenance', 'Maintenance'), ('governmental', 'Governmental'), ('fitout', 'Fit-out / Renovation')], max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='villa_category',
            field=models.CharField(blank=True, choices=[('residential', 'Residential Villa'), ('commercial', 'Commercial Villa')], max_length=40),
        ),
        migrations.AddField(
            model_name='siteplan',
            name='application_file',
            field=models.FileField(blank=True, null=True, upload_to='siteplans/applications/'),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='id_attachment',
            field=models.FileField(blank=True, null=True, upload_to='owners/ids/'),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='id_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='owner_name_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='owner_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='siteplanowner',
            name='share_percent',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='buildinglicense',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildinglicense',
            name='license_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='buildinglicense',
            name='plot_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='siteplan',
            name='base_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siteplan',
            name='land_use',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siteplan',
            name='overlay_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siteplan',
            name='plot_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='siteplanowner',
            name='right_hold_type',
            field=models.CharField(blank=True, default='Ownership', max_length=120),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_classification', models.CharField(blank=True, max_length=120)),
                ('contract_type', models.CharField(blank=True, max_length=120)),
                ('tender_no', models.CharField(blank=True, max_length=120)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('contractor_trade_license', models.CharField(blank=True, max_length=120)),
                ('total_project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_bank_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_owner_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('project_duration_months', models.PositiveIntegerField(default=0)),
                ('owner_includes_consultant', models.BooleanField(default=False)),
                ('owner_fee_design_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('owner_fee_supervision_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('owner_fee_extra_mode', models.CharField(blank=True, max_length=40)),
                ('owner_fee_extra_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bank_includes_consultant', models.BooleanField(default=False)),
                ('bank_fee_design_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bank_fee_supervision_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bank_fee_extra_mode', models.CharField(blank=True, max_length=40)),
                ('bank_fee_extra_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('license_snapshot', models.JSONField(default=dict, editable=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
