# Generated by Django 5.1.3 on 2025-11-05 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_license_file_ref_buildinglicense_land_plan_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinglicense',
            name='license_project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='license_project_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='owners',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_code',
            field=models.CharField(blank=True, db_index=True, help_text='Starts with M, followed by odd digits only (1,3,5,7,9).', max_length=40, validators=[django.core.validators.RegexValidator(message="Internal code must start with 'M' and contain odd digits only (1,3,5,7,9).", regex='^M[13579]*$')]),
        ),
    ]
