# Generated by Django 5.1.3 on 2025-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_buildinglicense_license_project_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildinglicense',
            old_name='consultant_license_no',
            new_name='design_consultant_license_no',
        ),
        migrations.RenameField(
            model_name='buildinglicense',
            old_name='consultant_name',
            new_name='design_consultant_name',
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='consultant_same',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='supervision_consultant_license_no',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='supervision_consultant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
