# Generated by Django 5.1.3 on 2025-11-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_consultant_license_no_buildinglicense_design_consultant_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Awarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('consultant_registration_number', models.CharField(blank=True, max_length=120)),
                ('project_number', models.CharField(blank=True, max_length=120)),
                ('contractor_registration_number', models.CharField(blank=True, max_length=120)),
                ('awarding_file', models.FileField(blank=True, null=True, upload_to='awarding/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awarding', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
