# Generated by Django 5.1.3 on 2025-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_contract_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_appendix_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/appendix/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_explanation_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/explanations/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/main/'),
        ),
    ]
