# Generated by Django 4.2.7 on 2025-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_contract_contract_appendix_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='start_order_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/start_orders/'),
        ),
    ]
