# Generated by Django 5.1.3 on 2025-11-21 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_start_order_file_to_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='internal_code',
            field=models.CharField(blank=True, db_index=True, help_text='Starts with M, digits allowed, last digit must be odd (1,3,5,7,9).', max_length=40, validators=[django.core.validators.RegexValidator(message="Internal code must start with 'M' and end with an odd digit (1,3,5,7,9).", regex='^M[0-9]*[13579]$')]),
        ),
    ]
