import { useMemo, useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { api } from "../../../services/api";
import Dialog from "../../../components/Dialog";
import Field from "../../../components/fields/Field";
import ViewRow from "../../../components/fields/ViewRow";
import PersonField from "../components/PersonField";
import ReadOnlyField from "../../../components/fields/ReadOnlyField";
import YesNoChips from "../../../components/YesNoChips";
import WizardShell from "../components/WizardShell";
import StepActions from "../components/StepActions";
import RtlSelect from "../../../components/fields/RtlSelect";
import InfoTip from "../components/InfoTip";
import Button from "../../../components/Button";
import FileAttachmentView from "../../../components/FileAttachmentView";
import useLicense, { normalizeOwner } from "../../../hooks/useLicense";
import { toIsoDate, formatProjectNumber } from "../../../utils/formatters";
import { formatLicenseServerErrors } from "../../../utils/errors/licenseErrorFormatter";
import { getErrorMessage } from "../../../utils/errorHandler";
import { toLocalizedUse, isRO } from "../../../utils/licenseHelpers";
import { saveToList } from "../../../utils/localStorage";
import { extractFileNameFromUrl } from "../../../utils/fileHelpers";

export default function LicenseStep({ projectId, onPrev, onNext, isView: isViewProp }) {
  const { t, i18n } = useTranslation();
  const isAR = /^ar\b/i.test(i18n.language || "");
  const { form, setF, owners, setOwners, existingId, setExistingId, isView: isViewState, setIsView } = useLicense(projectId, i18n);

  // ✅ توحيد السلوك: إذا كان isViewProp محدد من الخارج (من WizardPage)، نستخدمه مباشرة
  // الوضع الافتراضي هو التعديل (false) وليس الفيو
  const [viewMode, setViewMode] = useState(() => {
    // إذا كان isViewProp محدد صراحة (true أو false)، نستخدمه
    if (isViewProp !== undefined) return isViewProp === true;
    // إذا لم يكن محدد، نستخدم isViewState من الـ hook
    return isViewState === true;
  });
  const hasNextStep = typeof onNext === "function";
  
  // ✅ مزامنة مع isViewProp من الخارج
  useEffect(() => {
    if (isViewProp !== undefined) {
      setViewMode(isViewProp === true);
    } else {
      // إذا لم يكن محدد من الخارج، نستخدم isViewState من الـ hook
      setViewMode(isViewState === true);
    }
  }, [isViewProp, isViewState]);

  const updateViewMode = (next) => {
    setViewMode(next);
    // ✅ تحديث isViewState في الـ hook فقط إذا لم يكن isViewProp محدد من الخارج
    if (isViewProp === undefined) {
      setIsView(next);
    }
  };
  const [errorMsg, setErrorMsg] = useState("");
  const [buildingLicenseFileUrl, setBuildingLicenseFileUrl] = useState("");
  // ✅ تتبع ما إذا كان license_no تم إنشاؤه تلقائياً من license_project_no
  const [isLicenseNoAutoGenerated, setIsLicenseNoAutoGenerated] = useState(false);

  const readonlyHint = t("no_edit_source_siteplan");
  const licProjectNoLabel = t("license_project_no");

  // تحميل URL الملف المحفوظ والتحقق من العلاقة بين license_project_no و license_no
  useEffect(() => {
    if (!projectId || !existingId) return;
    (async () => {
      try {
        const { data } = await api.get(`projects/${projectId}/license/`);
        if (Array.isArray(data) && data.length > 0) {
          const licenseData = data[0];
          if (licenseData.building_license_file) {
            setBuildingLicenseFileUrl(licenseData.building_license_file);
          }
          
          // ✅ التحقق من العلاقة بين license_project_no و license_no
          if (licenseData.license_project_no && licenseData.license_no) {
            const expectedLicenseNo = licenseData.license_project_no + "-";
            if (licenseData.license_no === expectedLicenseNo || licenseData.license_no.startsWith(licenseData.license_project_no + "-")) {
              setIsLicenseNoAutoGenerated(true);
            }
          }
        }
      } catch (e) {}
    })();
  }, [projectId, existingId]);
  
  // ✅ عند تحميل البيانات من useLicense hook، نتحقق من العلاقة
  useEffect(() => {
    if (form.license_project_no && form.license_no) {
      const expectedLicenseNo = form.license_project_no + "-";
      // إذا كان license_no يبدأ بـ license_project_no + "-"، فهو تم إنشاؤه تلقائياً
      if (form.license_no === expectedLicenseNo || form.license_no.startsWith(form.license_project_no + "-")) {
        setIsLicenseNoAutoGenerated(true);
      } else {
        setIsLicenseNoAutoGenerated(false);
      }
    } else if (!form.license_project_no && !form.license_no) {
      setIsLicenseNoAutoGenerated(false);
    }
  }, [form.license_project_no, form.license_no]);

  const LICENSE_TYPES = useMemo(
    () => [
      { value: "new_build_empty_land", label: t("license_type") + " - " + t("license_type_new_build") },
      { value: "renovation", label: t("license_type_renovation") },
      { value: "extension", label: t("license_type_extension") },
    ],
    [t]
  );

  // بناء الحمولة
  const buildPayload = () => {
    const normalized = {
      ...form,
      issue_date: toIsoDate(form.issue_date),
      last_issue_date: toIsoDate(form.last_issue_date),
      expiry_date: toIsoDate(form.expiry_date),
      technical_decision_date: toIsoDate(form.technical_decision_date),
    };

    if (normalized.last_issue_date && normalized.issue_date) {
      const last = new Date(normalized.last_issue_date);
      const first = new Date(normalized.issue_date);
      if (last < first) {
        throw new Error(t("last_issue_date_error"));
      }
    }

    const fd = new FormData();
    Object.entries(normalized).forEach(([k, v]) => {
      if (v === null || v === undefined || v === "") return;
      if (typeof v === "object" && !(v instanceof File) && !(v instanceof Blob)) {
        fd.append(k, JSON.stringify(v));
      } else {
        fd.append(k, v);
      }
    });

    // ✅ لا نرسل owners - الرخصة تأخذ الملاك من السايت بلان تلقائياً
    // هذا يضمن أن الملاك موحدة في كل النظام

    if (form.building_license_file) {
      fd.append("building_license_file", form.building_license_file);
    }
    return fd;
  };

  // حفظ الاستشاري والمقاول في LocalStorage
  const saveAndNext = async () => {
    if (!projectId) {
      setErrorMsg(t("open_specific_project_to_save"));
      return;
    }

    try {
      // حفظ الاستشاري
      if (form.design_consultant_name && form.design_consultant_license_no) {
        saveToList("consultants", {
          name: form.design_consultant_name,
          license: form.design_consultant_license_no
        });
      }

      // حفظ المقاول
      if (form.contractor_name && form.contractor_license_no) {
        saveToList("contractors", {
          name: form.contractor_name,
          license: form.contractor_license_no
        });
      }

      const payload = buildPayload();

      if (existingId) {
        await api.patch(`projects/${projectId}/license/${existingId}/`, payload);
      } else {
        const { data: created } = await api.post(`projects/${projectId}/license/`, payload);
        if (created?.id) setExistingId(created.id);
      }

      setErrorMsg("");
      
      // ✅ بعد الحفظ الناجح، نعيد تحميل جميع البيانات من الخادم لضمان التزامن
      try {
        const { data } = await api.get(`projects/${projectId}/license/`);
        if (Array.isArray(data) && data.length > 0) {
          const licenseData = data[0];
          
          // تحديث form مع البيانات المحفوظة
          setF("building_license_file", null); // إزالة File object
          if (licenseData.building_license_file) {
            setBuildingLicenseFileUrl(licenseData.building_license_file);
          }
          
          // ✅ إعادة تحميل الملاك من السايت بلان لضمان التزامن
          try {
            const { data: spData } = await api.get(`projects/${projectId}/siteplan/`);
            if (Array.isArray(spData) && spData.length > 0 && Array.isArray(spData[0].owners)) {
              setOwners(spData[0].owners.map(normalizeOwner));
            }
          } catch (e) {
            console.error("Error reloading siteplan owners:", e);
          }
        }
      } catch (e) {
        console.error("Error reloading license data after save:", e);
        // لا نرمي خطأ هنا لأن الحفظ نجح بالفعل
      }
      
      updateViewMode(true);
      if (hasNextStep) {
        onNext();
      }
    } catch (err) {
      // محاولة استخدام formatLicenseServerErrors أولاً
      const serverData = err?.response?.data;
      const formatted = formatLicenseServerErrors(serverData);
      
      // إذا لم يكن هناك تنسيق محدد، استخدم معالج الأخطاء الموحد
      if (formatted) {
        setErrorMsg(formatted);
      } else {
        const errorMessage = getErrorMessage(err, "حفظ الرخصة");
        setErrorMsg(errorMessage || t("save_failed"));
      }
    }
  };

  return (
    <WizardShell title={t("wizard_step_license")}>
      <Dialog
        open={!!errorMsg}
        title={t("warning")}
        desc={<pre className="pre-wrap m-0">{errorMsg}</pre>}
        confirmLabel={t("ok")}
        onClose={() => setErrorMsg("")}
        onConfirm={() => setErrorMsg("")}
      />

      {viewMode && (
        <div className={`row ${isAR ? "justify-start" : "justify-end"} mb-12`}>
          <Button variant="secondary" onClick={() => updateViewMode(false)}>
            {t("edit")}
          </Button>
        </div>
      )}

      {/* 1) بيانات الرخصة */}
      <h4>{t("license_details")}</h4>
      {viewMode ? (
        <div className="form-grid cols-3">
          <ViewRow label={t("license_type")} value={LICENSE_TYPES.find(x => x.value === form.license_type)?.label || form.license_type} />
          <ViewRow label={licProjectNoLabel} value={form.license_project_no} />
          <ViewRow label={t("issue_date_first")} value={form.issue_date} />
          <ViewRow label={t("license_no")} value={form.license_no} />
          <Field label={t("attach_building_license")}>
            <FileAttachmentView
              fileUrl={buildingLicenseFileUrl}
              fileName={buildingLicenseFileUrl ? extractFileNameFromUrl(buildingLicenseFileUrl) : ""}
              projectId={projectId}
              endpoint={`projects/${projectId}/license/`}
            />
          </Field>
        </div>
      ) : (
        <div className="form-grid cols-3">
          <Field label={t("license_type")}>
            <div className="row row--align-center" style={{ gap: 8 }}>
              <RtlSelect
                className="rtl-select"
                options={LICENSE_TYPES}
                value={form.license_type}
                onChange={(v) => setF("license_type", v)}
                placeholder={t("select_license_type")}
              />
              <InfoTip align="start" text={t("note_take_data_as_in_license")} />
            </div>
          </Field>
          <Field label={licProjectNoLabel}>
            <input
              className="input"
              value={form.license_project_no}
              onChange={(e) => {
                const formatted = formatProjectNumber(e.target.value);
                setF("license_project_no", formatted);
                
                // ✅ إذا كان license_no فارغ أو تم إنشاؤه تلقائياً من قبل، نحدثه تلقائياً
                if (formatted) {
                  if (!form.license_no || isLicenseNoAutoGenerated) {
                    // نحدث license_no برقم المشروع + "-" في النهاية (لإكمال الرقم يدوياً)
                    setF("license_no", formatted + "-");
                    setIsLicenseNoAutoGenerated(true);
                  }
                } else {
                  // إذا تم حذف رقم المشروع، نحذف رقم الرخصة أيضاً إذا كان تم إنشاؤه تلقائياً
                  if (isLicenseNoAutoGenerated) {
                    setF("license_no", "");
                    setIsLicenseNoAutoGenerated(false);
                  }
                }
              }}
            />
          </Field>
          <Field label={t("issue_date_first")}>
            <input
              className="input"
              type="date"
              value={form.issue_date || ""}
              onChange={(e) => setF("issue_date", e.target.value)}
            />
          </Field>
          <Field label={t("license_no")}>
            <input
              className="input"
              value={form.license_no}
              onChange={(e) => {
                const newValue = e.target.value;
                setF("license_no", newValue);
                // ✅ إذا قام المستخدم بتعديل license_no يدوياً، نوقف التحديث التلقائي
                const expectedAutoValue = form.license_project_no + "-";
                if (newValue !== expectedAutoValue) {
                  setIsLicenseNoAutoGenerated(false);
                }
              }}
            />
          </Field>
          <Field label={t("attach_building_license")}>
            <div>
              {/* عرض الملف المرفق سابقاً إذا كان موجوداً */}
              {buildingLicenseFileUrl && !form.building_license_file && (
                <div className="mini mb-8">
                  {t("current_file")}: {extractFileNameFromUrl(buildingLicenseFileUrl)}
                </div>
              )}
              <div className="row row--align-center row--gap-8">
                <input
                  className="input"
                  type="file"
                  onChange={(e) => setF("building_license_file", e.target.files?.[0] || null)}
                />
                <InfoTip align="start" text={t("please_attach_building_license")} />
              </div>
              {/* عرض الملف الجديد المختار */}
              {form.building_license_file && form.building_license_file instanceof File && (
                <div className="mini mt-8 text-primary">
                  {t("file_selected")}: {form.building_license_file.name}
                </div>
              )}
            </div>
          </Field>
        </div>
      )}

      {/* 2) بيانات الأرض */}
      <h4 className="mt-16">{t("land_details")}</h4>
      {viewMode ? (
        <div className="form-grid cols-4">
          <ViewRow label={t("zone")} value={form.zone} />
          <ViewRow label={t("sector")} value={form.sector} />
          <ViewRow label={t("plot_no")} value={form.plot_no} />
          <ViewRow label={t("plot_area_sqm")} value={form.plot_area_sqm} />
          <ViewRow label={t("land_use")} value={toLocalizedUse(form.land_use, i18n.language)} />
          <ViewRow label={t("land_use_sub")} value={toLocalizedUse(form.land_use_sub, i18n.language)} />
          <ViewRow label={t("plot_address")} value={form.plot_address} />
        </div>
      ) : (
        <div className="form-grid cols-4">
          <ReadOnlyField
            label={t("zone")}
            value={form.zone}
            hint={isRO("zone") ? readonlyHint : ""}
          />
          <ReadOnlyField
            label={t("sector")}
            value={form.sector}
            hint={isRO("sector") ? readonlyHint : ""}
          />
          <ReadOnlyField
            label={t("plot_no")}
            value={form.plot_no}
            hint={isRO("plot_no") ? readonlyHint : ""}
          />
          <ReadOnlyField
            label={t("plot_area_sqm")}
            value={form.plot_area_sqm}
            hint={isRO("plot_area_sqm") ? readonlyHint : ""}
          />
          <ReadOnlyField
            label={t("land_use")}
            value={form.land_use}
            hint={isRO("land_use") ? readonlyHint : ""}
          />
          <ReadOnlyField
            label={t("land_use_sub")}
            value={form.land_use_sub}
            hint={isRO("land_use_sub") ? readonlyHint : ""}
          />
          <ReadOnlyField
            label={t("plot_address")}
            value={form.plot_address}
            hint={isRO("plot_address") ? readonlyHint : ""}
          />
        </div>
      )}

      {/* 3) بيانات الملاك */}
      <h4 className="mt-16">{t("owner_details")}</h4>
      {owners && owners.length ? (
        owners.map((o, i) => (
          <div key={i} className="owner-block">
            <div className="form-grid cols-3">
              <Field label={t("owner_name_ar")}>
                {viewMode ? (
                  <div>{o.owner_name_ar || t("empty_value")}</div>
                ) : (
                  <input className="input readonly" readOnly value={o.owner_name_ar || ""} title={readonlyHint} />
                )}
              </Field>
              <Field label={t("owner_name_en")}>
                {viewMode ? (
                  <div>{o.owner_name_en || t("empty_value")}</div>
                ) : (
                  <input className="input readonly" readOnly value={o.owner_name_en || ""} title={readonlyHint} />
                )}
              </Field>
              <div />
            </div>
          </div>
        ))
      ) : (
        <div className="row row--align-center row--gap-8 mt-8">
          <InfoTip align="start" text={t("no_owners_in_siteplan")} />
        </div>
      )}

      {/* 4) الاستشاري */}
      <h4 className="mt-16">{t("consultant_details")}</h4>
      <Field label={t("consultant_same_question")}>
        <YesNoChips
          value={form.consultant_same ? "yes" : "no"}
          onChange={(v) => {
            const same = v === "yes";
            setF("consultant_same", same);
            if (same) {
              setF("supervision_consultant_name", form.design_consultant_name);
              setF("supervision_consultant_license_no", form.design_consultant_license_no);
            } else {
              setF("supervision_consultant_name", "");
              setF("supervision_consultant_license_no", "");
            }
          }}
        />
      </Field>

      <h4 className="mt-16">{t("design_consultant")}</h4>
      <div className="form-grid cols-4">
        <PersonField
          type="consultant"
          label={t("consultant")}
          licenseLabel={t("consultant_lic")}
          nameValue={form.design_consultant_name}
          licenseValue={form.design_consultant_license_no}
          onNameChange={(v) => {
            setF("design_consultant_name", v);
            if (form.consultant_same) {
              setF("supervision_consultant_name", v);
            }
          }}
          onLicenseChange={(v) => {
            setF("design_consultant_license_no", v);
            if (form.consultant_same) {
              setF("supervision_consultant_license_no", v);
            }
          }}
          isView={viewMode}
          onSelect={(c) => {
            if (form.consultant_same) {
              setF("supervision_consultant_name", c.name);
              setF("supervision_consultant_license_no", c.license);
            }
          }}
        />
      </div>

      {!form.consultant_same && (
        <>
          <h4 className="mt-16">{t("supervision_consultant")}</h4>
          <div className="form-grid cols-4">
            <PersonField
              type="consultant"
              label={t("consultant")}
              licenseLabel={t("consultant_lic")}
              nameValue={form.supervision_consultant_name}
              licenseValue={form.supervision_consultant_license_no}
              onNameChange={(v) => setF("supervision_consultant_name", v)}
              onLicenseChange={(v) => setF("supervision_consultant_license_no", v)}
              isView={viewMode}
            />
          </div>
        </>
      )}

      {/* 5) المقاول */}
      <h4 className="mt-16">{t("contractor_details")}</h4>
      <div className="form-grid cols-4">
        <PersonField
          type="contractor"
          label={t("contractor")}
          licenseLabel={t("contractor_lic")}
          nameValue={form.contractor_name}
          licenseValue={form.contractor_license_no}
          onNameChange={(v) => setF("contractor_name", v)}
          onLicenseChange={(v) => setF("contractor_license_no", v)}
          isView={viewMode}
        />
      </div>

      {!viewMode && (
        <StepActions
          onPrev={onPrev}
          onNext={saveAndNext}
          nextLabel={hasNextStep ? undefined : t("save")}
        />
      )}
    </WizardShell>
  );
}
